---
title: "Body_fat_Prediction"
author: "Naveen"
date: "5/26/2022"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
## Read data from a .csv file ##
women <- read.csv("C:/Users/morla/Downloads/dataset_RG.csv")
Dat <- women[,c(1,2,3,4,5,6,7)]
```


```{r}
summary(Dat)

```


```{r}
#norm_scale <- predict(process, as.data.frame(Dat))
data1 <- as.data.frame(scale(Dat))

## Fit MLR model
mlr <- lm(WomenBodyFat ~ . , data = Dat)
summary(mlr)
```


```{r}
mlr5 <- lm(WomenBodyFat ~ . , data = data1)
summary(mlr5)

```


```{r}
## 95% Confidence interval for model parameters ##
confint(mlr, level = 0.95)

```


```{r}
## Scatter plot ##
plot(Dat$Age, Dat$WomenBodyFat, main = "Relationship between WomenBodyFat and Age",
     xlab = "Age", ylab = "WomenBodyFat")

```
```{r}
plot(Dat$Height, Dat$WomenBodyFat, main = "Relationship between WomenBodyFat and Weight",
     xlab = "Height", ylab = "WomenBodyFat")

```


```{r}
plot(Dat$WaistCircumference, Dat$WomenBodyFat, main = "Relationship between WomenBodyFat and WaistCircumference",
     xlab = "WaistCircumference", ylab = "WomenBodyFat")

```


```{r}
plot(Dat$HipCircumference, Dat$WomenBodyFat, main = "Relationship between WomenBodyFat and HipCircumference",
     xlab = "HipCircumference", ylab = "WomenBodyFat")

```


```{r}
plot(Dat$ChestCircumference, Dat$WomenBodyFat, main = "Relationship between WomenBodyFat and ChestCircumference",
     xlab = "ChestCircumference", ylab = "WomenBodyFat")

```


```{r}
plot(Dat$UpperarmCircumference, Dat$WomenBodyFat, main = "Relationship between WomenBodyFat and UpperarmCircumference",
     xlab = "UpperarmCircumference", ylab = "WomenBodyFat")

```


```{r}
pairs(Dat)
```



```{r}
## Type I ANOVA ##
res.aov.IA <- aov(WomenBodyFat ~ ., data = Dat)
summary(res.aov.IA)

```
```{r}
res.aov.IB <- aov(WomenBodyFat ~  ., data = Dat)
summary(res.aov.IB)
```


```{r}
## Type II and III ANOVA ##
library(car)
Anova(mlr, type=2)

```
```{r}
Anova(mlr, type=3)
```


```{r}
############################
### Removing high cor regrossor ###
############################

library(car)
vif(mlr)

```

```{r}
cor(Dat)
```


```{r}
library(StepReg)
stepwise(Dat, y="WomenBodyFat", selection = "forward", select = "adjRsq")


```


```{r}
Dat<-Dat[,c(1,2,3,4,5)]
## Fit MLR model
mlr2 <- lm(WomenBodyFat ~ . , data = Dat)
summary(mlr2)
```


```{r}
vif(mlr2)

```

```{r}
library(car)
Anova(mlr2, type=2)
```


```{r}
par(mfcol = c(2,3))
plot(Dat$Age, mlr2$residuals, 
     main = "Check for linearity \n Residuals vs. Age")
abline(h=0)
plot(Dat$Height, mlr2$residuals, 
     main = "Check for linearity \n Residuals vs. Height")
abline(h=0)
plot(Dat$WaistCircumference, mlr2$residuals, 
     main = "Check for linearity \n Residuals vs. WaistCircumference")
abline(h=0)
plot(Dat$HipCircumference, mlr2$residuals, 
     main = "Check for linearity \n Residuals vs. HipCircumference")
abline(h=0)
```


```{r}
## Check for independence of random error
par(mfcol = c(2,3))
row_num <- c(1:nrow(Dat))
sort_x1 <- sort(Dat$Age, index.return=TRUE)
plot(row_num, mlr2$residuals[sort_x1$ix], 
     main = "Check for independence  Residuals sorted by Age")
abline(h=0)
```


```{r}
sort_x2 <- sort(Dat$Height, index.return=TRUE)
plot(row_num, mlr2$residuals[sort_x2$ix], 
     main = "Check for independence \n Residuals sorted by Height")
abline(h=0)

```
```{r}
sort_x3 <- sort(Dat$WaistCircumference, index.return=TRUE)
plot(row_num, mlr2$residuals[sort_x3$ix], 
     main = "Check for independence \n Residuals sorted by WaistCircumference")
abline(h=0)

```
```{r}
sort_x4 <- sort(Dat$HipCircumference, index.return=TRUE)
plot(row_num, mlr2$residuals[sort_x4$ix], 
     main = "Check for independence \n Residuals sorted by HipCircumference")
abline(h=0)
```


```{r}
## Check for zero mean and constant variance of random error
plot(mlr2$fitted.values, mlr2$residuals, 
     main = "Check for 0 mean and constant var \n  Residual vs. fitted value")
abline(h=0)

```

```{r}
## Check for normality of random error
qqnorm(mlr2$residuals)
qqline(mlr2$residuals)
```


```{r}
############################
### Apply Transformation(we are not applying this because this is not useful for us) ###
############################

mlr2 <- lm(log(WomenBodyFat) ~ ., data=Dat)
summary(mlr2)
```


```{r}
## Check for normality of random error
qqnorm(mlr2$residuals)
qqline(mlr2$residuals)
```


```{r}
vif(mlr2)
```
```{r}
cor(Dat)

```

```{r}
par(mfcol = c(2,3))
plot(Dat$Age, mlr2$residuals, 
     main = "Check for linearity \n Residuals vs. Age")
abline(h=0)
plot(Dat$Height, mlr2$residuals, 
     main = "Check for linearity \n Residuals vs. Height")
abline(h=0)
plot(Dat$WaistCircumference, mlr2$residuals, 
     main = "Check for linearity \n Residuals vs. WaistCircumference")
abline(h=0)
plot(Dat$HipCircumference, mlr2$residuals, 
     main = "Check for linearity \n Residuals vs. HipCircumference")
abline(h=0)
#plot(Dat$ChestCircumference, mlr2$residuals, 
   #  main = "Check for linearity \n Residuals vs. ChestCircumference")
abline(h=0)
#plot(Dat$UpperarmCircumference, mlr2$residuals, 
 #    main = "Check for linearity \n Residuals vs. UpperarmCircumference")
abline(h=0)

```


```{r}
############################
### removing outlier ###
############################

mlr$residuals
which.max(abs(mlr$residuals))
```


```{r}
############################
### removing outlier ###
############################
## Find high leverage points
k=4
n =136
hv <- hatvalues(mlr2)
which(hv > (2*(k+1)/n))
row_num <- c(1:136)

```
```{r}
plot(row_num, hv, xlab = "row number",
     ylab = "hatvalues", 
     main = "Identification of high leverage points")
abline(h = (2*(k+1)/n))

```


```{r}
#outliers
### Use internally standardized residuals (rstandard)
r1 <- rstandard(mlr2)
which(abs(r1) > 3)
row_num <- c(1:136)

```
```{r}
plot(c(1,21), c(-6, 6), xlab = "row number",
     ylab = "internally studentized residuals", 
     main = "Identification of outlier points",
     type = "n")
points(row_num, r1)
abline(h = 3)
abline(h = -3)
```


```{r}
### Use externally standardized residuals (rstudent)
r2 <- rstudent(mlr2)
which(abs(r2) > 3)
row_num <- c(1:136)

```
```{r}
plot(c(1,21), c(-3.5, 3.5), xlab = "row number",
     ylab = "externally studentized residuals", 
     main = "Identification of outlier points",
     type = "n")
points(row_num, r2)
abline(h = 3)
abline(h = -3)
```


```{r}
### Find influential points ###
###############################

### Use difference in fits (dffits)
d <- dffits(mlr2) #influential if abs(dffits) > 2*sqrt((k+2)/(n-k-2))
which(abs(d) > 2*sqrt((k+2)/(n-k-2)))
row_num <- c(1:136)

```
```{r}
plot(c(1,21), c(-9, 1),  xlab = "row number",
     ylab = "deffits", 
     main = "Identification of influential points", type = "n")
points(row_num, d)
abline(h = 2*sqrt((k+2)/(n-k-2)))
abline(h = - 2*sqrt((k+2)/(n-k-2)))
```


```{r}
### Use Cook's distance (cooks.distance)
cd <- cooks.distance(mlr2) #influential if d > 1
which(cd > 1)
row_num <- c(1:136)

```

```{r}
plot(row_num, cd, xlab = "row number",
     ylab = "Cook's distance", 
     main = "Identification of influential points")
abline(h = 1)
```

```{r}
### Use COVRATIO (covratio)
cv <- covratio(mlr2) #influential if covratio > 1 + 3*(k+1)/n OR covratio < 1 - 3*(k+1)/n
which(cv > (1 + 3*(k+1)/n))
which(cv < (1 - 3*(k+1)/n))
row_num <- c(1:136)

```
```{r}
plot(row_num, cv, xlab = "row number",
     ylab = "covratio", 
     main = "Identification of influential points")
abline(h = (1 + 3*(k+1)/n))
abline(h = (1 - 3*(k+1)/n))
```


```{r}
cols <- character(nrow(Dat))
## Remove Obs 66
dat3 <- Dat[-c(44,51,66,73,98),]
mlr3 <- lm((WomenBodyFat) ~ . , data = dat3)
summary(mlr3) #unusual x1 and x2
vif(mlr3)
```


```{r}
## 95% Confidence interval for model parameters ##
confint(mlr3, level = 0.95)

```


```{r}
## Scatter plot ##
plot(dat3$Age, dat3$WomenBodyFat, main = "Relationship between WomenBodyFat and Age",
     xlab = "Age", ylab = "WomenBodyFat")


```
```{r}
plot(dat3$Height, dat3$WomenBodyFat, main = "Relationship between WomenBodyFat and Weight",
     xlab = "Height", ylab = "WomenBodyFat")

```
```{r}
plot(dat3$WaistCircumference, dat3$WomenBodyFat, main = "Relationship between WomenBodyFat and WaistCircumference",
     xlab = "WaistCircumference", ylab = "WomenBodyFat")

```
```{r}
plot(dat3$HipCircumference, dat3$WomenBodyFat, main = "Relationship between WomenBodyFat and HipCircumference",
     xlab = "HipCircumference", ylab = "WomenBodyFat")
```

```{r}
par(mfcol = c(2,3))
plot(dat3$Age, mlr3$residuals, 
     main = "Check for linearity \n Residuals vs. Age")
abline(h=0)
plot(dat3$Height, mlr3$residuals, 
     main = "Check for linearity \n Residuals vs. Height")
abline(h=0)
plot(dat3$WaistCircumference, mlr3$residuals, 
     main = "Check for linearity \n Residuals vs. WaistCircumference")
abline(h=0)
plot(dat3$HipCircumference, mlr3$residuals, 
     main = "Check for linearity \n Residuals vs. HipCircumference")
abline(h=0)
```


```{r}
## Check for independence of random error
par(mfcol = c(1, 1))
row_num <- c(1:nrow(dat3))
sort_x1 <- sort(dat3$Age, index.return=TRUE)
plot(row_num, mlr3$residuals[sort_x1$ix], 
     main = "Check for independence \n Residuals sorted by Age")
abline(h=0)

```

```{r}
sort_x2 <- sort(dat3$Height, index.return=TRUE)
plot(row_num, mlr3$residuals[sort_x2$ix], 
     main = "Check for independence \n Residuals sorted by Height")
abline(h=0)

```
```{r}
sort_x3 <- sort(dat3$WaistCircumference, index.return=TRUE)
plot(row_num, mlr3$residuals[sort_x3$ix], 
     main = "Check for independence \n Residuals sorted by WaistCircumference")
abline(h=0)

```
```{r}
sort_x4 <- sort(dat3$HipCircumference, index.return=TRUE)
plot(row_num, mlr3$residuals[sort_x4$ix], 
     main = "Check for independence \n Residuals sorted by HipCircumference")
abline(h=0)
```

```{r}
## Check for zero mean and constant variance of random error
plot(mlr3$fitted.values, mlr3$residuals, 
     main = "Check for 0 mean and constant var \n  Residual vs. fitted value")
abline(h=0)
```


```{r}


## Check for normality of random error
qqnorm(mlr3$residuals)
qqline(mlr3$residuals)

```


```{r}
shapiro.test(mlr3$residuals)

```


